name: Quote Bot CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run YAPF to test if python code is correctly formatted
        uses: AlexanderMelde/yapf-action@v2.0
        with:
          args: --verbose

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run OWASP Noir
        id: noir
        uses: owasp-noir/noir@v1.1.0
        with:
          base_path: '.'
      - name: Display results
        run: echo '${{ steps.noir.outputs.endpoints }}' | jq .

  build-and-push:
    name: Build and push to Docker Hub
    needs: [security-scan, formatting-check]
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код бота
        uses: actions/checkout@v4

      - name: Логинимся в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка и пуш Docker образа
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: leor156/quote-bot:latest

  name: Telegram Gate

  deploy:
    name: Deploy to VPS via Ansible
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код репозитория (чтобы получить файл deploy.yml)
        uses: actions/checkout@v4

      - name: Запускаем Ansible плейбук
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: A_deploy.yml
          key: ${{ secrets.SERVER_SSH_KEY }}
          options: |
            -i ${{ secrets.SERVER_HOST }},
            -u ${{ secrets.SERVER_USER }}
            --extra-vars "TOKEN=${{ secrets.TOKEN }} ADMIN_IDS=${{ secrets.WADMIN_IDS }}"


      - name: Notifier
        uses: ethyaan/tgate-action@v1.0.0
        if: always()
        with:
          token: ${{ secrets.token_A }} # savethe bot token at settings/secrets with name: token
          to: ${{ secrets.ADMIN_IDS }} # save your chat id at settings/secrets with name: chat
          thread_id: ${{secrets.threadid}} # set this for sending message in thread or group topic
          disable_web_page_preview: false # set this to true to disable link previw in telegram
          disable_notification: false # set tjis true to send message in silet mode

